//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.TwitterSampleData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class TwitterSampleData { }
#else

	public class TwitterSampleData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public TwitterSampleData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/TwitterWall;component/SampleData/TwitterSampleData/TwitterSampleData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Tweets _Tweets = new Tweets();

		public Tweets Tweets
		{
			get
			{
				return this._Tweets;
			}
		}

		private string _Keyword = string.Empty;

		public string Keyword
		{
			get
			{
				return this._Keyword;
			}

			set
			{
				if (this._Keyword != value)
				{
					this._Keyword = value;
					this.OnPropertyChanged("Keyword");
				}
			}
		}
	}

	public class TweetsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _CreatedAt = string.Empty;

		public string CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}

			set
			{
				if (this._CreatedAt != value)
				{
					this._CreatedAt = value;
					this.OnPropertyChanged("CreatedAt");
				}
			}
		}

		private string _Text = string.Empty;

		public string Text
		{
			get
			{
				return this._Text;
			}

			set
			{
				if (this._Text != value)
				{
					this._Text = value;
					this.OnPropertyChanged("Text");
				}
			}
		}

		private System.Windows.Media.ImageSource _ProfileImage = null;

		public System.Windows.Media.ImageSource ProfileImage
		{
			get
			{
				return this._ProfileImage;
			}

			set
			{
				if (this._ProfileImage != value)
				{
					this._ProfileImage = value;
					this.OnPropertyChanged("ProfileImage");
				}
			}
		}

		private string _FromUser = string.Empty;

		public string FromUser
		{
			get
			{
				return this._FromUser;
			}

			set
			{
				if (this._FromUser != value)
				{
					this._FromUser = value;
					this.OnPropertyChanged("FromUser");
				}
			}
		}
	}

	public class Tweets : System.Collections.ObjectModel.ObservableCollection<TweetsItem>
	{ 
	}
#endif
}
